config = {
    "abilities": [
        {
            "key": "q",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 738, "top": 869, "width": 15, "height": 15},
            "directional": False,
        },
        {
            "key": "e",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 777, "top": 869, "width": 15, "height": 15},
            "directional": False,
        },
        {
            "key": "f",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 816, "top": 869, "width": 15, "height": 15},
            "directional": False,
        },
        {
            "key": "r",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": True,
            "castTime": 1900,
            "position": {"left": 855, "top": 869, "width": 15, "height": 15},
            "directional": False,
        },
        {
            "key": "1",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "esoteric": True,
            "cooldown": 20000,
            "position": {"left": 759, "top": 907, "width": 15, "height": 15},
            "directional": True,
        },
        {
            "key": "2",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 797, "top": 907, "width": 15, "height": 15},
            "directional": False,
        },
        {
            "key": "3",
            "abilityType": "normal",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 835, "top": 907, "width": 15, "height": 15},
            "directional": False,
        },
        {
            "key": "4",
            "abilityType": "normal",
            "hold": True,
            "holdTime": 3000,
            "cast": False,
            "castTime": None,
            "esoteric": True,
            "cooldown": 16000,
            "position": {"left": 873, "top": 907, "width": 15, "height": 15},
            "directional": False,
        },
        {
            "key": "v",
            "abilityType": "awakening",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 691, "top": 894, "width": 19, "height": 11},
            "directional": False,
        },
        {
            "key": "z",
            "abilityType": "specialty1",
            "hold": False,
            "holdTime": None,
            "cast": False,
            "castTime": None,
            "position": {"left": 895, "top": 839, "width": 13, "height": 12},
            "directional": False,
        },
    ],
    "interact": "g",
    "move": "left",
    "blink": "space",
    "meleeAttack": "c",
    "awakening": "v",
    "healthPot": '"',
    "healthPotAtPercent": 0.7,
    "useAwakening": True,
    "useSpeciality1": False,
    "useSpeciality2": False,
    "autoRepair": True,
    "shortcutEnterChaos": True,
    "useHealthPot": True,
    "floor3": True,
    "usePotion": False,
    "skipLogin": False,
    "endTime": False,
    "regions": {
        "minimap": (1655, 170, 260, 200),  # (1700, 200, 125, 120)
        "abilities": (625, 779, 719, 155),
        "leaveMenu": (0, 154, 250, 300),
    },
    "screenResolutionX": 1920,
    "screenResolutionY": 1080,
    "clickableAreaX": 500,
    "clickableAreaY": 250,
    "screenCenterX": 960,
    "screenCenterY": 540,
    "minimapCenterX": 1772,
    "minimapCenterY": 272,
    "timeLimit": 360000,
    "delayedStart": 3000,
    "healthCheckX": 690,
    "healthCheckY": 854,
}
